# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://keweilu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
imageurl: "https://source.unsplash.com/collection/880012/2000x500"
portrait: "/assets/img/portrait.jpeg"

# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings

configuration:
  title: Kewei Lu
  yoursitetitle: Kewei Lu
  email_address: lukewei07@gmail.com
  footer_text: >
   Kewei Lu

  # icons
  email_address: lukewei07@gmail.com
  linkedin: https://www.linkedin.com/in/kewei-lu-216b433a/
  github: https://github.com/keweilu

# social icons and sharing options
social:
  - icon: envelope-square
    url: lukewei07@gmail.com
    desc:	Email
    share_url:
    share_title:
    share_link:
  - icon:	linkedin
    url:	https://www.linkedin.com/in/kewei-lu-216b433a/
    desc:	Linkedin
    share_url:
    share_title:
    share_link:
  - icon:	github
    url:	https://github.com/keweilu
    desc:	github
    share_url:
    share_title:
    share_link:
  - icon: scholar
    url:	https://scholar.google.com/citations?user=ZU82-J0AAAAJ&hl=en
    desc:	Google Scholar
    share_url:
    share_title:
    share_link:
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
